INSERT INTO [dbo].[TargetedSites]
           ([Name]
           ,[Domain]
           ,[Url])
VALUES
    ('Google','https://www.google.com/','http://www.google.com/add_1.html'),
    ('Facebook','https://www.facebook.com/','http://www.facebook.com/add_1.html'),
    ('Twitter','https://twitter.com/','http://www.twitter.com/add_1.html'),
    ('Youtube','https://www.youtube.com/','http://www.youtube.com/add_1.html'),
    ('Whatsapp','https://www.whatsapp.com/','http://www.whatsapp.com/add_1.html'),
    ('Instagram','http://www.instagram.com/','http://www.instagram.com/add_1.html'),
    ('Linkedin','http://www.linkedin.com/','http://www.linkedin.com/add_1.html'),
    ('Snapchat','https://www.snapchat.com/','http://www.snapchat.com/add_1.html'),
    ('Pinterest','http://pinterest.com/','http://www.pinterest.com/add_1.html'),
    ('Redit','https://www.reddit.com/','http://www.reddit.com/add_1.html'),
    ('Wechat','http://www.wechat.com/','http://www.wechat.com/add_1.html'),
    ('Baidu','http://tieba.baidu.com/','http://www.baidu.com/add_1.html'),
    ('Viber','http://www.viber.com/','http://www.viber.com/add_1.html'),
    ('Qzone','http://qzone.qq.com/','http://www.qzone.com/add_1.html'),
    ('Tumblr','http://tumblr.com/','http://www.tumblr.com/add_1.html'),
    ('Skype','http://skype.com/','http://www.skype.com/add_1.html'),
    ('Weibo','http://weibo.com/','http://www.weibo.com/add_1.html'),
    ('Qq','http://www.qq.com/','http://www.qq.com/add_1.html'),
    ('Line','http://line.me/','http://www.line.com/add_1.html')